# Generated by Django 2.1.7 on 2019-04-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleshipSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTurn', models.CharField(max_length=100)),
                ('player1LiveShips', models.CharField(max_length=20)),
                ('player2LiveShips', models.CharField(max_length=20)),
                ('player1SunkShips', models.CharField(max_length=20)),
                ('player2SunkShips', models.CharField(max_length=20)),
                ('player1MissedMissiles', models.CharField(max_length=300)),
                ('player2MissedMissiles', models.CharField(max_length=300)),
                ('player1HitMissiles', models.CharField(max_length=300)),
                ('player2HitMissiles', models.CharField(max_length=300)),
                ('gameWinner', models.CharField(max_length=100)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
