# Generated by Django 2.1.7 on 2019-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleshipsession',
            name='waitingForPlayer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
