# Generated by Django 2.1.7 on 2019-04-20 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_battleshipsession_waitingforplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleshipsession',
            name='currentTurn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currentTurn', to=settings.AUTH_USER_MODEL),
        ),
    ]
