# Generated by Django 2.1.7 on 2019-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190424_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleshipsession',
            name='player1ShipHealth',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battleshipsession',
            name='player2ShipHealth',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
