# Generated by Django 2.1.7 on 2019-04-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190426_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleshipsession',
            name='gameWinner',
            field=models.CharField(max_length=100),
        ),
    ]
