# Generated by Django 2.1.7 on 2019-04-27 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190426_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleshipsession',
            name='currentTurn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentTurn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='battleshipsession',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='battleshipsession',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
